name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4
    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    # Build the plugin jar using Gradle
    - name: Build plugin jar
      run: ./gradlew jar
    # Upload the built jar file as an artifact
    - name: Upload built jar file
      uses: actions/upload-artifact@v4
      with:
        name: plugin-jar
        path: build/libs/*.jar
